# Generated by Django 3.0.6 on 2020-06-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province_source', models.CharField(max_length=20)),
                ('Province_destination', models.CharField(max_length=20)),
                ('Amount', models.IntegerField()),
                ('Date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('News_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Time', models.CharField(max_length=30)),
                ('Province', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('Province_source', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Province_destination', models.CharField(max_length=20)),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
