# Generated by Django 3.0.6 on 2020-06-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
            ],
        ),
    ]
