"""
Django settings for epdimic project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#af=rc0y3x426f7s*%(a=i8jd+600mu5mt=(wa++rlyat_3o)x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',

    'Group06.users',
    'Group06.news',

    'Group07',
    'Group09',
    'Group08',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'epdimic.urls'
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

EMAIL_HOST = 'smtp.qq.com'  # 如果是 163 改成 smtp.163.com
EMAIL_PORT = 465
EMAIL_HOST_USER = '1156609896@qq.com'  # 在这里填入您的QQ邮箱账号
EMAIL_HOST_PASSWORD = 'erzfezlybfxsgibe'  # 请在这里填上您自己邮箱的授权码
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USE_SSL = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+'/templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'epdimic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        'NAME': 'epidemic',  # 数据库名
        'USER': 'se2020',  # 账号
        'PASSWORD': 'Epidemic_2020',  # 密码
        'HOST': '49.235.194.16',  # HOST
        'POST': 3306,  # 端口
    },
    'db1': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'case_surveillance',
        'USER':'alice',
        "PASSWORD":'12345678',
        'HOST':'epidemic-case-demo.mysql.rds.aliyuncs.com',
        'PORT':'3306',
    },
    'db_g6': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        'NAME': 'epidemic',  # 数据库名
        'USER': 'se2020',  # 账号
        'PASSWORD': 'Epidemic_2020',  # 密码
        'HOST': '49.235.194.16',  # HOST
        'POST': 3306,  # 端口

    }
}

DATABASES_APPS_MAPPING = {
    'Group7': 'db1',
    'Group9': 'db1',
    'Group8': 'db1',
    # 'users': 'db2',
}

DATABASE_ROUTERS = ['dbRouter.db_router.DatabaseAppsRouter']


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#cors
CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = (

    'http://*',

)

CORS_ALLOW_METHODS = (

    'DELETE',

    'GET',

    'OPTIONS',

    'PATCH',

    'POST',

    'PUT',

    'VIEW',

)


CORS_ALLOW_HEADERS = (

    'accept',

    'XMLHttpRequest',

    'X_FILENAME',

    'accept-encoding',

    'authorization',

    'content-type',

    'dnt',

    'origin',

    'user-agent',

    'x-csrftoken',

    'x-requested-with',

    'Pragma',

    'X-Custom-Header',

    'sessionid',

    'User',

)




# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')  #可搜集到一个目录下，方便后续部署
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "templates","static"),    #公共静态文件目录，可以被搜集到上面的STATIC_ROOT下
)

# 用户表
AUTH_USER_MODEL = 'users.UserInfo'



# G6 邮箱验证的前端链接
EMAIL_VERIFY_URL = 'http://127.0.0.1:3000/'


DEFAULT_SUPERUSER_INFO = {
    'phone': '15111111111',
    'real_name': 'superUser',
    'citizen_id': '500000000000000000'
}
